---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atlas
description: "Fedora Silverblue based image with built-in DoD CAC support."
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: containerfile
    snippets:
      - |
        LABEL org.opencontainers.image.title="Atlas"
        LABEL org.opencontainers.image.description="Fedora Silverblue + CAC baked-in (OpenSC, DoD trust, Firefox RPM)"
        LABEL org.opencontainers.image.source="https://github.com/large-farva/atlas"
        LABEL org.opencontainers.image.licenses="Apache-2.0"

  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - firefox
      - pcsc-lite
      - pcsc-lite-ccid
      - pcsc-tools
      - opensc
      - p11-kit
      - p11-kit-trust
      - nss-tools
      - ca-certificates
      - unzip
      - openssl
      - curl

  - type: systemd
    system:
      enabled:
        - pcscd.socket
  
  - type: dod-trust
    source: local
    
  - type: script
    scripts:
      - remove-packages.sh
      - dconf.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Papers
          - org.gnome.Loupe
          - com.github.rafostar.Clapper
          - io.github.nokse22.inspector
          - org.signal.Signal
          - com.mattjakeman.ExtensionManager
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
          - com.usebottles.bottles
          - org.onlyoffice.desktopeditors
          - com.raggesilver.BlackBox
        remove:
          - org.gnome.Evince
          - org.gnome.eog
          - org.gnome.Totem
          - org.gnome.Extensions
          - org.mozilla.firefox

  - type: signing
