---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# Most packages and a couple Flatpaks are already installed by Aurora.
# Keeping them here for documentation purposes for Kinoite migration.

name: outpost
description: "uBlue Aurora based image with built-in DoD CAC support."
base-image: ghcr.io/ublue-os/aurora-nvidia
image-version: latest

modules:
  - type: containerfile
    snippets:
      - |
        LABEL org.opencontainers.image.title="Outpost"
        LABEL org.opencontainers.image.description="uBlue Aurora based image with built-in DoD CAC support."
        LABEL org.opencontainers.image.source="https://github.com/large-farva/outpost"
        LABEL org.opencontainers.image.licenses="Apache-2.0"

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      skip-unavailable: true
      packages:
        - ca-certificates
        - curl
        - firefox
        - git
        - nss-tools
        - opensc
        - openssl
        - p11-kit
        - p11-kit-trust
        - pcsc-lite
        - pcsc-lite-ccid
        - pcsc-tools
        - plymouth-plugin-script
        - unzip
        - okular
        - poppler
        - poppler-utils

    remove:
      packages:
        - fedora-bookmarks
        - kairpods
        - openrazer*
        - Sunshine
        - tmux
        - vim*

  - type: systemd
    system:
      enabled:
        - pcscd.socket
    user:
      enabled:
        - firefox-module.service

  - type: script
    scripts:
      - dod-trust.sh
      - plymouth.sh
      
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.github.tchx84.Flatseal
          - de.hohnstaedt.xca
          - io.github.DenysMb.Kontainer
          - io.github.flattool.Warehouse
          - org.onlyoffice.desktopeditors
          - org.signal.Signal
        remove:
          - com.ranfdev.DistroShelf
          - org.kde.okular
          - org.mozilla.firefox
  
  - type: os-release
    properties:
      ID: outpost
      ID_LIKE: fedora
      NAME: Outpost
      PRETTY_NAME: Outpost 43
      VARIANT: CAC Workstation
      VARIANT_ID: cac-workstation
      VERSION_CODENAME: watchtower
      HOME_URL: https://github.com/large-farva/outpost
      DOCUMENTATION_URL: https://github.com/large-farva/outpost
      SUPPORT_URL: https://github.com/large-farva/outpost/issues
      BUG_REPORT_URL: https://github.com/large-farva/outpost/issues
      LOGO: outpost-logo
      IMAGE_ID: outpost
      IMAGE_VERSION: latest
      DEFAULT_HOSTNAME: outpost

  - type: initramfs
  
  - type: signing
