---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# Working on Kinoite migration.

# TODO: offer multiple images for hardware compatability

name: outpost
description: "Fedora Kinoite based image with built-in DoD CAC support."
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 43

modules:
  - type: containerfile
    snippets:
      - |
        LABEL org.opencontainers.image.title="Outpost"
        LABEL org.opencontainers.image.description="Fedora Kinoite based image with built-in DoD CAC support."
        LABEL org.opencontainers.image.source="https://github.com/large-farva/outpost"
        LABEL org.opencontainers.image.licenses="Apache-2.0"

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - distrobox
        - fastfetch
        - gettext
        - git
        - nss-tools
        - okular
        - pcsc-tools
        - starship
    remove:
      packages:
        - fedora-bookmarks
        - toolbox
      
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.github.tchx84.Flatseal
          - de.hohnstaedt.xca
          - io.github.DenysMb.Kontainer
          - io.github.flattool.Warehouse
          - org.onlyoffice.desktopeditors
          - org.signal.Signal
        remove:
          - org.kde.okular
          - org.mozilla.Thunderbird
  
  - type: fonts
    fonts:
      nerd-fonts:
        - AdwaitaMono
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - pcscd.socket
        - outpost-motd.service
    user:
      enabled:
        - firefox-module.service

  - type: script
    scripts:
      - dod-trust.sh
      - cleanup.sh

  - type: os-release
    properties:
      NAME: Outpost
      ID: outpost
      ID_LIKE: fedora
      VERSION_CODENAME: Watchtower
      PRETTY_NAME: Outpost 43
      LOGO: outpost-logo
      DEFAULT_HOSTNAME: outpost
      VARIANT: Kinoite
      VARIANT_ID: outpost
      IMAGE_ID: outpost
      IMAGE_VERSION: latest-43
      
      HOME_URL: https://github.com/large-farva/outpost
      DOCUMENTATION_URL: https://github.com/large-farva/outpost
      SUPPORT_URL: https://github.com/large-farva/outpost/issues
      BUG_REPORT_URL: https://github.com/large-farva/outpost/issues

  - type: initramfs
  
  - type: signing
