---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: outpost
description: "Fedora Silverblue based image with built-in DoD CAC support."
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: containerfile
    snippets:
      - |
        LABEL org.opencontainers.image.title="Outpost"
        LABEL org.opencontainers.image.description="Fedora Silverblue based image with built-in DoD CAC support."
        LABEL org.opencontainers.image.source="https://github.com/large-farva/outpost"
        LABEL org.opencontainers.image.licenses="Apache-2.0"

  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - ca-certificates
      - curl
      - firefox
      - nss-tools
      - opensc
      - openssl
      - p11-kit
      - p11-kit-trust
      - pcsc-lite
      - pcsc-lite-ccid
      - pcsc-tools
      - unzip

  - type: systemd
    system:
      enabled:
        - pcscd.socket

  - type: script
    scripts:
      - dconf.sh
      - install-dod-trust.sh
      - plymouth.sh
      - remove-packages.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.github.rafostar.Clapper
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.raggesilver.BlackBox
          - com.usebottles.bottles
          - io.github.flattool.Warehouse
          - io.github.nokse22.inspector
          - it.mijorus.gearlever
          - org.gnome.Loupe
          - org.gnome.Papers
          - org.onlyoffice.desktopeditors
          - org.signal.Signal
        remove:
          - org.gnome.Evince
          - org.gnome.Extensions
          - org.gnome.Totem
          - org.gnome.eog
          - org.mozilla.firefox

  - type: signing
