---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atlas
# description will be included in the image's metadata
description: Fedora Silverblue based image with built-in DoD CAC support.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - firefox
      - pcsc-lite
      - pcsc-lite-ccid
      - pcsc-tools
      - opensc
      - p11-kit
      - p11-kit-trust
      - nss-tools
      - ca-certificates
      - unzip
      - openssl
      - curl

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Papers
          - org.gnome.Loupe
          - com.github.rafostar.Clapper
          - io.github.nokse22.inspector
          - org.signal.Signal
          - com.mattjakeman.ExtensionManager
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
          - com.usebottles.bottles
          - org.onlyoffice.desktopeditors
        remove:
          - org.gnome.Evince
          - org.gnome.eog
          - org.gnome.Totem
          - org.gnome.Extensions
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

