name: atlas
description: Fedora Silverblue based image with built-in DoD CAC support.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - firefox
      - pcsc-lite
      - pcsc-lite-ccid
      - pcsc-tools
      - opensc
      - p11-kit
      - p11-kit-trust
      - nss-tools
      - ca-certificates
      - unzip
      - openssl
      - curl
  
  - type: systemd
    system:
      enabled:
        - pcscd.socket

  - type: script
    scripts:
      - files/scripts/install-dod-trust.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Papers
          - org.gnome.Loupe
          - com.github.rafostar.Clapper
          - io.github.nokse22.inspector
          - org.signal.Signal
          - com.mattjakeman.ExtensionManager
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
          - com.usebottles.bottles
          - org.onlyoffice.desktopeditors
        remove:
          - org.gnome.Evince
          - org.gnome.eog
          - org.gnome.Totem
          - org.gnome.Extensions

  - type: signing
