---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: outpost
description: "Fedora Kinoite based image with built-in DoD CAC support."
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: containerfile
    snippets:
      - |
        LABEL org.opencontainers.image.title="Outpost"
        LABEL org.opencontainers.image.description="Fedora Kinoite based image with built-in DoD CAC support."
        LABEL org.opencontainers.image.source="https://github.com/large-farva/outpost"
        LABEL org.opencontainers.image.licenses="Apache-2.0"

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - ca-certificates
        - curl
        - nss-tools
        - opensc
        - openssl
        - p11-kit
        - p11-kit-trust
        - pcsc-lite
        - pcsc-lite-ccid
        - pcsc-tools
        - plymouth-plugin-script
        - unzip

    remove:
      packages:
        - fedora-bookmarks
        - fedora-chromium-config*
        - tmux
        - vim*

  - type: systemd
    system:
      enabled:
        - pcscd.socket

    user:
      enabled:
        - p11-kit-server.socket

  - type: script
    scripts:
      - dod-trust.sh
      - plymouth.sh
      - os-release.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.github.tchx84.Flatseal
          - io.github.DenysMb.Kontainer
          - io.github.flattool.Warehouse
          - io.github.kolunmi.Bazaar
          - org.chromium.Chromium
          - org.onlyoffice.desktopeditors
          - org.signal.Signal

  - type: signing
