#!/usr/bin/env bash
# System Bash defaults; user settings belong in ~/.bashrc.

if [[ -z ${BASHRCSOURCED:-} ]]; then
    BASHRCSOURCED=Y

    if [[ $- == *i* ]]; then
        if [[ -z ${PROMPT_COMMAND:-} ]]; then
            declare -a PROMPT_COMMAND
            case ${TERM:-} in
                xterm*)
                    if [[ -e /etc/sysconfig/bash-prompt-xterm ]]; then
                        PROMPT_COMMAND=(/etc/sysconfig/bash-prompt-xterm)
                    else
                        # Prompt variables must expand when the prompt is drawn.
                        # shellcheck disable=SC2016
                        PROMPT_COMMAND=('printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"')
                    fi
                    ;;
                screen*)
                    if [[ -e /etc/sysconfig/bash-prompt-screen ]]; then
                        PROMPT_COMMAND=(/etc/sysconfig/bash-prompt-screen)
                    else
                        # Prompt variables must expand when the prompt is drawn.
                        # shellcheck disable=SC2016
                        PROMPT_COMMAND=('printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"')
                    fi
                    ;;
                *)
                    if [[ -e /etc/sysconfig/bash-prompt-default ]]; then
                        PROMPT_COMMAND=(/etc/sysconfig/bash-prompt-default)
                    fi
                    ;;
            esac
        fi
        shopt -s histappend checkwinsize
        # Starship replaces this fallback prompt when available.
        PS1='[\u@\h:\l \W]\$ '
    fi

    if ! shopt -q login_shell; then
        # Profile scripts call pathmunge while they are sourced.
        # shellcheck disable=SC2329
        pathmunge() {
            case ":${PATH}:" in
                *:"$1":*) ;;
                *)
                    if [[ ${2:-} == after ]]; then
                        PATH=$PATH:$1
                    else
                        PATH=$1:$PATH
                    fi
                    ;;
            esac
        }
        if [[ $(umask) == 0000 ]]; then
            umask 022
        fi
        SHELL=/bin/bash
        for i in /etc/profile.d/*.sh; do
            if [[ -r "$i" ]]; then
                if [[ $- == *i* ]]; then
                    # shellcheck source=/dev/null
                    source "$i"
                else
                    # shellcheck source=/dev/null
                    source "$i" >/dev/null
                fi
            fi
        done
        unset i
        unset -f pathmunge
    fi
fi
